name: pipeline CI/CD

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
      
    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar pruebas
      run: npm test
      
    - name: Iniciar sesión en Azure
      if: ${{ job.status == 'success' }}
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Configurar CLI de Azure
      run: az configure --defaults acr=acrAndresMayor
    
    - name: Configurar entorno de Docker
      uses: azure/docker-login@v1
      with:
        login-server: acrandresmayor.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Construir y etiquetar la imagen de Docker
      run: |
        docker build -t frontend .
        docker tag frontend acrandresmayor.azurecr.io/frontend:${{ github.sha }}
        
    - name: Subir imagen al ACR
      run: docker push acrandresmayor.azurecr.io/frontend:${{ github.sha }}
    
    - name: kubectl-simple
      uses: steebchen/kubectl@v2.1.1
      with:
        config: ${{ secrets.KUBECONFIG }} 
        command: set image -n proyecto deployment/front front=acrandresmayor.azurecr.io/frontend:${{ github.sha }}
      
      
